# Dossier contenant les vcf.
vcf_folder_name: vcf

# Sera le nom du dossier study
cancer_study_identifier: nom_study

# Pointe vers un ou plusieur fichier texte
# exemples:
# colon: NGS colon-lung échantillons COLONS_anapath.txt
# lung: NGS colon-lung échantillons POUMONS_anapath.txt
study:
    - data/test/list_anapath.txt

# Dépendance du script
anapath_patient: corresp_patientid_anapath09-11-17.csv

case_list:
    name: nom de case liste
    description: description de case liste

meta_study:
    # lung: nsclc, colon: coadread
    type_of_cancer: 'coadread'
    description: ~ 
    name: ~
    short_name: colung
    add_global_case_list: true

meta_samples:
    genetic_alteration_type: CLINICAL
    datatype: SAMPLE_ATTRIBUTES
    data_filename: data_samples.txt

meta_patients:
    genetic_alteration_type: CLINICAL
    datatype: PATIENT_ATTRIBUTES
    data_filename: data_patients.txt

meta_mutations_extended:
    genetic_alteration_type: MUTATION_EXTENDED
    datatype: MAF
    stable_id: mutations
    show_profile_in_analysis_tab: true
    profile_name: Mutations
    profile_description: Mutation profile
    data_filename: mutations.maf
    swissprot_identifier: name

